### ISSUE TITLE
Leaks password via `beet config`

### ISSUE THREAD

**Issue by ryanakca** [nolsto/beets-follow#7]
Unlike the `musicbrainz` plugin, the `follow` plugin will leak passwords via `beet config`. Please redact the password instead.

```yaml
<rak@:/tmp/c:26> beet config | egrep -A3 '(musicbrainz|follow)'
musicbrainz:
    user: ryanakca
    pass: REDACTED
    auto: yes
--
follow:
    email: aobeu
    password: aoeuaoeuaeu
mbcollection:
```
